# Compound shell

## Import packages

In [1]:
import pandas as pd
import numpy as np
from astropy import constants
from astronavigation.deflection import *
from astronavigation.planets import Body, SolarSystem
import numpy.linalg as LA

np.set_printoptions(precision=54)

## Useful constants

In [2]:
pc = constants.pc.to('km').value
AU = constants.au.to('km').value
c = constants.c.to('km/s').value
eps = 1/c

# Create Solar System
ss = SolarSystem()

jupiter = ss.getPlanet('jupiter')
r_jup_arc = 20  # mean jupiter radius in arcseconds

sun = ss.getSun()

## Read and clean data

Read data

In [3]:
# path
path = 'Stars_GareqEvent2017_oneTransit_new2.dat'

# read, use delimiter='\s+' to choose every white space as delimiter
stars_data = pd.read_table(path, delimiter='\s+')

# display
pd.set_option('display.max_columns', None)
stars_data.head(10)

tAF5         tAFx               starId     etaS[deg]  sig_eta[mas]  \
0  2017.145239  2017.145239  3631075715518049024  4.475043e-01      0.099969   
1  2017.145239  2017.145239  3631485528413582336 -5.870432e-01      0.072845   
2  2017.145239  2017.145239  3631191099815174272  1.157136e-01      0.091820   
3  2017.145239  2017.145239  3631256894418771584 -1.456322e-01      0.096824   
4  2017.145239  2017.145239  3631266072764288000 -2.651681e-01      0.103025   
5  2017.145239  2017.145239  3631298199119733504 -5.711045e-01      0.076116   
6  2017.145239  2017.145239  3631241265033227392 -5.069712e-02      0.074388   
7  2017.145239  2017.145239  3631239925003381248 -1.514225e-07      0.100975   
8  2017.145239  2017.145239  3631255107712373376 -2.825577e-01      0.065251   
9  2017.145239  2017.145239  3631145740665759616  6.684247e-02      0.093621   

   zetaS[deg]  sig_zeta[mas]  etaJup[deg]  zetaJup[deg]  etaSpin[deg]  \
0    0.149847       0.372775     0.012973      0.020895     20.471557   
1    0.052752       0.312333     0.012973      0.020895     20.471557   
2    0.075482       0.339177     0.012973      0.020895     20.471557   
3   -0.074359       0.311625     0.012973      0.020895     20.471557   
4   -0.023983       0.389037     0.012973      0.020895     20.471557   
5    0.208823       0.297541     0.012973      0.020895     20.471557   
6    0.185999       0.254893     0.012973      0.020895     20.471557   
7   -0.000004       0.368185     0.012973      0.020895     20.471557   
8    0.157291       0.272657     0.012973      0.020895     20.471557   
9   -0.075513       0.311841     0.012973      0.020895     20.471557   

   zetaSpin[deg]  jupPosGCX[m]  jupPosGCY[m]  jupPosGCZ[m]   gaiaPosX[m]  \
0      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
1      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
2      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
3      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
4      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
5      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
6      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
7      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
8      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
9      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   

    gaiaPosY[m]   gaiaPosZ[m]  long_jupGC[deg]  lat_jupGC[deg]  \
0  6.053463e+10  2.630360e+10       201.426291       -7.396121   
1  6.053463e+10  2.630360e+10       201.426291       -7.396121   
2  6.053463e+10  2.630360e+10       201.426291       -7.396121   
3  6.053463e+10  2.630360e+10       201.426291       -7.396121   
4  6.053463e+10  2.630360e+10       201.426291       -7.396121   
5  6.053463e+10  2.630360e+10       201.426291       -7.396121   
6  6.053463e+10  2.630360e+10       201.426291       -7.396121   
7  6.053463e+10  2.630360e+10       201.426291       -7.396121   
8  6.053463e+10  2.630360e+10       201.426291       -7.396121   
9  6.053463e+10  2.630360e+10       201.426291       -7.396121   

   long_gaia[deg]  lat_gaia[deg]  starRA[deg]  starDec[deg]  
0       155.66443      10.151667   201.552776     -7.831722  
1       155.66443      10.151667   201.463499     -6.796371  
2       155.66443      10.151667   201.480483     -7.499324  
3       155.66443      10.151667   201.331641     -7.236695  
4       155.66443      10.151667   201.383427     -7.117590  
5       155.66443      10.151667   201.620517     -6.813578  
6       155.66443      10.151667   201.593303     -7.333806  
7       155.66443      10.151667   201.405330     -7.382970  
8       155.66443      10.151667   201.566250     -7.101704  
9       155.66443      10.151667   201.328604     -7.449173

Create queary for source_id and add parallaxes to the data

In [4]:
# not need to evaluate this cell if new data has been already downloaded
with open('query.txt', 'w') as f:
    
    star_id = stars_data['starId'].unique()
    query = 'SELECT *\nFROM gaiaedr3.gaia_source\nWHERE '
    
    for id in star_id:
        query += f'source_id = {id} '
        if id != star_id[-1]:
            query += 'OR '
    f.write(query)

In [5]:
# parallax and parallax erro are in mas
new_data = pd.read_csv('1654093971685O-result.csv')
new_data = new_data[['source_id', 'parallax', 'parallax_error']]
new_data = new_data.set_index('source_id')
new_data

parallax  parallax_error
source_id                                     
3631075715518049024   3.409062        0.032620
3631089188831339264   5.459490        0.035637
3631095407943986048   0.243898        0.018328
3631096438736162944   0.535781        0.026916
3631145740665759616   1.217448        0.033738
3631186628753669888   0.400931        0.014865
3631191099815174272   1.352386        0.018157
3631239925003381248   0.472181        0.016357
3631241265033227392   0.758436        0.020345
3631244559272698112   0.488491        0.018010
3631244937229820800   2.545210        0.030274
3631255107712373376   3.914919        0.023334
3631256894418771584   6.970485        0.017854
3631266072764288000   1.330410        0.015664
3631298199119733504   1.593033        0.015341
3631485528413582336  10.354598        0.184979

In [6]:
# add parallax
parallax = []
parallax_err = []
for id in stars_data['starId']:
    p = new_data['parallax']
    err = new_data['parallax_error']
    parallax.append(p.loc[id])
    parallax_err.append(err.loc[id])
stars_data['parallax[mas]'] = parallax
stars_data['parallax_err[mas]'] = parallax_err
stars_data

tAF5         tAFx               starId  etaS[deg]  sig_eta[mas]  \
0    2017.145239  2017.145239  3631075715518049024   0.447504      0.099969   
1    2017.145239  2017.145239  3631485528413582336  -0.587043      0.072845   
2    2017.145239  2017.145239  3631191099815174272   0.115714      0.091820   
3    2017.145239  2017.145239  3631256894418771584  -0.145632      0.096824   
4    2017.145239  2017.145239  3631266072764288000  -0.265168      0.103025   
..           ...          ...                  ...        ...           ...   
137  2017.145239  2017.145240  3631095407943986048   0.228960      0.071818   
138  2017.145239  2017.145240  3631244559272698112  -0.088713      0.049222   
139  2017.145239  2017.145240  3631244937229820800  -0.079046      0.054070   
140  2017.145239  2017.145240  3631089188831339264   0.347718      0.055859   
141  2017.145239  2017.145240  3631096438736162944   0.142424      0.046130   

     zetaS[deg]  sig_zeta[mas]  etaJup[deg]  zetaJup[deg]  etaSpin[deg]  \
0      0.149847       0.372775     0.012973      0.020895     20.471557   
1      0.052752       0.312333     0.012973      0.020895     20.471557   
2      0.075482       0.339177     0.012973      0.020895     20.471557   
3     -0.074359       0.311625     0.012973      0.020895     20.471557   
4     -0.023983       0.389037     0.012973      0.020895     20.471557   
..          ...            ...          ...           ...           ...   
137    0.058662       0.318960     0.012963      0.020873     19.823930   
138   -0.037527       0.220813     0.012963      0.020873     19.823930   
139    0.050917       0.226070     0.012963      0.020873     19.823930   
140    0.045807       0.233511     0.012963      0.020873     19.823930   
141    0.081247       0.184189     0.012963      0.020873     19.823930   

     zetaSpin[deg]  jupPosGCX[m]  jupPosGCY[m]  jupPosGCZ[m]   gaiaPosX[m]  \
0        22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
1        22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
2        22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
3        22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
4        22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
..             ...           ...           ...           ...           ...   
137      22.785597 -6.550931e+11 -2.570747e+11 -9.134985e+10 -1.338483e+11   
138      22.785597 -6.550931e+11 -2.570747e+11 -9.134985e+10 -1.338483e+11   
139      22.785597 -6.550931e+11 -2.570747e+11 -9.134985e+10 -1.338483e+11   
140      22.785597 -6.550931e+11 -2.570747e+11 -9.134985e+10 -1.338483e+11   
141      22.785597 -6.550931e+11 -2.570747e+11 -9.134985e+10 -1.338483e+11   

      gaiaPosY[m]   gaiaPosZ[m]  long_jupGC[deg]  lat_jupGC[deg]  \
0    6.053463e+10  2.630360e+10       201.426291       -7.396121   
1    6.053463e+10  2.630360e+10       201.426291       -7.396121   
2    6.053463e+10  2.630360e+10       201.426291       -7.396121   
3    6.053463e+10  2.630360e+10       201.426291       -7.396121   
4    6.053463e+10  2.630360e+10       201.426291       -7.396121   
..            ...           ...              ...             ...   
137  6.053366e+10  2.630318e+10       201.426269       -7.396111   
138  6.053366e+10  2.630318e+10       201.426269       -7.396111   
139  6.053366e+10  2.630318e+10       201.426269       -7.396111   
140  6.053366e+10  2.630318e+10       201.426269       -7.396111   
141  6.053366e+10  2.630318e+10       201.426269       -7.396111   

     long_gaia[deg]  lat_gaia[deg]  starRA[deg]  starDec[deg]  parallax[mas]  \
0        155.664430      10.151667   201.552776     -7.831722       3.409062   
1        155.664430      10.151667   201.463499     -6.796371      10.354598   
2        155.664430      10.151667   201.480483     -7.499324       1.352386   
3        155.664430      10.151667   201.331641     -7.236695       6.970485   
4       

Evaluate impact parameter

In [7]:
# star and jupiter coordinates
star = np.array([stars_data['etaS[deg]'], stars_data['zetaS[deg]']])
jup = np.array([stars_data['etaJup[deg]'], stars_data['zetaJup[deg]']])

# impact parameter in units of jupiter radius
stars_data['b_J'] = np.linalg.norm(star - jup, axis=0) * 3600 / r_jup_arc 

Evaluate proper motion

In [8]:
# proper motion is in mas/yr
pm_df = pd.read_csv('1654093971685O-result.csv')
pm_df = pm_df[['source_id', 'pmra', 'pmdec']]
pm_df = pm_df.set_index('source_id')
# add proper motion
pm_ra = []
pm_dec = []
for id in stars_data['starId']:
    ra_dot = pm_df['pmra']
    dec_dot = pm_df['pmdec']
    pm_ra.append(ra_dot.loc[id])
    pm_dec.append(dec_dot.loc[id])
stars_data['pmRA[mas/yr]'] = pm_ra
stars_data['pmDEC[mas/yr]'] = pm_dec
stars_data.head()

tAF5         tAFx               starId  etaS[deg]  sig_eta[mas]  \
0  2017.145239  2017.145239  3631075715518049024   0.447504      0.099969   
1  2017.145239  2017.145239  3631485528413582336  -0.587043      0.072845   
2  2017.145239  2017.145239  3631191099815174272   0.115714      0.091820   
3  2017.145239  2017.145239  3631256894418771584  -0.145632      0.096824   
4  2017.145239  2017.145239  3631266072764288000  -0.265168      0.103025   

   zetaS[deg]  sig_zeta[mas]  etaJup[deg]  zetaJup[deg]  etaSpin[deg]  \
0    0.149847       0.372775     0.012973      0.020895     20.471557   
1    0.052752       0.312333     0.012973      0.020895     20.471557   
2    0.075482       0.339177     0.012973      0.020895     20.471557   
3   -0.074359       0.311625     0.012973      0.020895     20.471557   
4   -0.023983       0.389037     0.012973      0.020895     20.471557   

   zetaSpin[deg]  jupPosGCX[m]  jupPosGCY[m]  jupPosGCZ[m]   gaiaPosX[m]  \
0      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
1      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
2      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
3      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
4      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   

    gaiaPosY[m]   gaiaPosZ[m]  long_jupGC[deg]  lat_jupGC[deg]  \
0  6.053463e+10  2.630360e+10       201.426291       -7.396121   
1  6.053463e+10  2.630360e+10       201.426291       -7.396121   
2  6.053463e+10  2.630360e+10       201.426291       -7.396121   
3  6.053463e+10  2.630360e+10       201.426291       -7.396121   
4  6.053463e+10  2.630360e+10       201.426291       -7.396121   

   long_gaia[deg]  lat_gaia[deg]  starRA[deg]  starDec[deg]  parallax[mas]  \
0       155.66443      10.151667   201.552776     -7.831722       3.409062   
1       155.66443      10.151667   201.463499     -6.796371      10.354598   
2       155.66443      10.151667   201.480483     -7.499324       1.352386   
3       155.66443      10.151667   201.331641     -7.236695       6.970485   
4       155.66443      10.151667   201.383427     -7.117590       1.330410   

   parallax_err[mas]         b_J  pmRA[mas/yr]  pmDEC[mas/yr]  
0           0.032620   81.587075    -57.337299     -22.363290  
1           0.184979  108.155070    -99.783487       9.701552  
2           0.018157   20.941453     -9.999470       4.156140  
3           0.017854   33.301944    -76.473223      -7.650200  
4           0.015664   50.712957     -5.287082      -0.106522

In [9]:
# shift alpha and delta
conv = 1e-3/3600  # from mas to deg

stars_data['starRA[deg]_new'] = stars_data['starRA[deg]'] + stars_data['pmRA[mas/yr]']*(stars_data['tAFx']-2016.0)*conv
stars_data['starDec[deg]_new'] = stars_data['starDec[deg]'] + stars_data['pmDEC[mas/yr]']*(stars_data['tAFx']-2016.0)*conv

Evaluate parallax displacement

In [10]:
# need to transform mas to m^-1
conv = 1e-6/pc  # 1e-3/(pc*1e3)
# useful quantities
alpha = np.deg2rad(stars_data['starRA[deg]_new'])
delta = np.deg2rad(stars_data['starDec[deg]_new'])
X = stars_data['gaiaPosX[m]']
Y = stars_data['gaiaPosY[m]']
Z = stars_data['gaiaPosZ[m]']
omega = stars_data['parallax[mas]']

d_alpha = omega*(1/np.cos(delta))*(X*np.sin(alpha) - Y*np.cos(alpha)) * conv
d_delta = omega*(X*np.cos(alpha)*np.sin(delta) +Y*np.sin(alpha)*np.sin(delta) - Z*np.cos(delta)) * conv

star_gaia_dir = np.array([np.cos(alpha + d_alpha)*np.cos(delta + d_delta), np.sin(alpha + d_alpha)*np.cos(delta + d_delta), np.sin(delta + d_delta)])
star_gaia_dir = star_gaia_dir

In [11]:
# add d_alpha, d_delta
stars_data['dRA[deg]'] = np.rad2deg(d_alpha)
stars_data['dDEC[deg]'] = np.rad2deg(d_delta)

# add star_gaia_dir
stars_data['starGCdirX'] = star_gaia_dir[0]
stars_data['starGCdirY'] = star_gaia_dir[1]
stars_data['starGCdirZ'] = star_gaia_dir[2]

Evaluate theta

In [12]:
# useful values
eta_s = np.deg2rad(stars_data['etaS[deg]'])
zeta_s = np.deg2rad(stars_data['zetaS[deg]'])
eta_J = np.deg2rad(stars_data['etaJup[deg]'])
zeta_J = np.deg2rad(stars_data['zetaJup[deg]'])

# gnomonic coordinates
# cos_psi = np.sin(zeta_J)*np.sin(zeta_s) + np.cos(zeta_J)*np.cos(zeta_s)*np.cos(eta_J - eta_s)
# the previous factor can be neglected because we take the fraction
x_g = np.cos(zeta_J)*np.sin(eta_J - eta_s)
y_g = np.sin(zeta_J)*np.cos(zeta_s) - np.cos(zeta_J)*np.sin(zeta_s)*np.cos(eta_J - eta_s)
theta = np.arctan2(y_g,x_g)
stars_data['theta'] = theta

In [13]:
theta

0     -2.853116
1     -0.053039
2     -2.653213
3      0.540839
4      0.159972
         ...   
137   -2.968396
138    0.521361
139   -0.315617
140   -3.067247
141   -2.705232
Length: 142, dtype: float64

Display data

In [14]:
stars_data.head(10)

tAF5         tAFx               starId     etaS[deg]  sig_eta[mas]  \
0  2017.145239  2017.145239  3631075715518049024  4.475043e-01      0.099969   
1  2017.145239  2017.145239  3631485528413582336 -5.870432e-01      0.072845   
2  2017.145239  2017.145239  3631191099815174272  1.157136e-01      0.091820   
3  2017.145239  2017.145239  3631256894418771584 -1.456322e-01      0.096824   
4  2017.145239  2017.145239  3631266072764288000 -2.651681e-01      0.103025   
5  2017.145239  2017.145239  3631298199119733504 -5.711045e-01      0.076116   
6  2017.145239  2017.145239  3631241265033227392 -5.069712e-02      0.074388   
7  2017.145239  2017.145239  3631239925003381248 -1.514225e-07      0.100975   
8  2017.145239  2017.145239  3631255107712373376 -2.825577e-01      0.065251   
9  2017.145239  2017.145239  3631145740665759616  6.684247e-02      0.093621   

   zetaS[deg]  sig_zeta[mas]  etaJup[deg]  zetaJup[deg]  etaSpin[deg]  \
0    0.149847       0.372775     0.012973      0.020895     20.471557   
1    0.052752       0.312333     0.012973      0.020895     20.471557   
2    0.075482       0.339177     0.012973      0.020895     20.471557   
3   -0.074359       0.311625     0.012973      0.020895     20.471557   
4   -0.023983       0.389037     0.012973      0.020895     20.471557   
5    0.208823       0.297541     0.012973      0.020895     20.471557   
6    0.185999       0.254893     0.012973      0.020895     20.471557   
7   -0.000004       0.368185     0.012973      0.020895     20.471557   
8    0.157291       0.272657     0.012973      0.020895     20.471557   
9   -0.075513       0.311841     0.012973      0.020895     20.471557   

   zetaSpin[deg]  jupPosGCX[m]  jupPosGCY[m]  jupPosGCZ[m]   gaiaPosX[m]  \
0      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
1      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
2      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
3      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
4      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
5      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
6      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
7      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
8      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
9      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   

    gaiaPosY[m]   gaiaPosZ[m]  long_jupGC[deg]  lat_jupGC[deg]  \
0  6.053463e+10  2.630360e+10       201.426291       -7.396121   
1  6.053463e+10  2.630360e+10       201.426291       -7.396121   
2  6.053463e+10  2.630360e+10       201.426291       -7.396121   
3  6.053463e+10  2.630360e+10       201.426291       -7.396121   
4  6.053463e+10  2.630360e+10       201.426291       -7.396121   
5  6.053463e+10  2.630360e+10       201.426291       -7.396121   
6  6.053463e+10  2.630360e+10       201.426291       -7.396121   
7  6.053463e+10  2.630360e+10       201.426291       -7.396121   
8  6.053463e+10  2.630360e+10       201.426291       -7.396121   
9  6.053463e+10  2.630360e+10       201.426291       -7.396121   

   long_gaia[deg]  lat_gaia[deg]  starRA[deg]  starDec[deg]  parallax[mas]  \
0       155.66443      10.151667   201.552776     -7.831722       3.409062   
1       155.66443      10.151667   201.463499     -6.796371      10.354598   
2       155.66443      10.151667   201.480483     -7.499324       1.352386   
3       155.66443      10.151667   201.331641     -7.236695       6.970485   
4       155.66443      10.151667   201.383427     -7.117590       1.330410   
5       155.66443      10.151667   201.620517     -6.813578       1.593033   
6       155.66443      10.151667   201.593303     -7.333806       0.758436   
7       155.66443      10.151667   201.405330     -7.382970       0.472181   
8       155.66443      10.151667   201.566250     -7.101704

### Find target stars

In [15]:
# threshold
thr = 5

# create threshold column
stars_data['thr'] = stars_data['b_J'] <= thr

# print number of targets
stars_data['thr'].value_counts()

False    133
True       9
Name: thr, dtype: int64

### Create target and reference dataframe

In [16]:
def ref_targ_split(df):
    
    filt = df['thr']

    target_df = df.loc[filt]
    reference_df = df.loc[(~filt)]
    
    return target_df, reference_df

## Evaluate deflection

In [17]:
# define epochs
epochs = stars_data['tAFx'].unique()

In [18]:
# differences
shell=[]
shell_q=[]
dt_new = []

# loop over epochs
for epoch in epochs:
    
    # take only data for the given epoch
    filt = stars_data['tAFx'] == epoch
    stars_epoch = stars_data.loc[filt]
    
    # split into target and reference
    target_df, reference_df = ref_targ_split(stars_epoch)
    
    theta_target = target_df['theta'].to_numpy()
    theta_reference = reference_df['theta'].to_numpy()
    
    bj_target = target_df['b_J'].to_numpy()
    bj_reference = reference_df['b_J'].to_numpy()
    
    
    shell_epoch = np.zeros((len(target_df), len(reference_df)))
    shell_q_epoch = np.zeros((len(target_df), len(reference_df)))
    
    
    # create body
    x_b = np.array([stars_epoch['jupPosGCX[m]'], stars_epoch['jupPosGCY[m]'], stars_epoch['jupPosGCZ[m]']]).T / 1000# in km
    
    # spin = cartesian(stars_epoch['etaSpin[deg]'].iloc[0], stars_epoch['zetaSpin[deg]'].iloc[0])
    
    body = Body(mass=jupiter.mass,
                pos=x_b[0],
                radius=jupiter.radius,
                J2=jupiter.J2,
                s=np.array([0, 0, 1])) 
    
    # sun
    x_sun = -np.array([stars_epoch['gaiaPosX[m]'], stars_epoch['gaiaPosY[m]'], stars_epoch['gaiaPosZ[m]']]).T/1000 # in km
    
    sun = Body(mass=sun.mass,
               pos=x_sun[0],
               radius=sun.radius)
    
    ##################
    #
    # print
    #
    ##################
    print(f'\n---------- epoch: {epoch} ----------\n')
    
    # loop over target
    x_targ = np.array([target_df['starGCdirX'], target_df['starGCdirY'], target_df['starGCdirZ']]).T
    for i in range(len(target_df)):
        
        # direction
        l0 = x_targ[i]
        
        # triplet
        t, n, m = on_triplet(l0, body.pos)
        
        # deflection
        defl_tar = deflection_mod3(l0, body.pos, eps, body.mass)
        dp_eta_tar = defl_tar * np.cos(theta_target[i])
        
        # deflection quadrupole
        dp1_tar, dp2_tar = deflection_mod3(l0, body.pos, eps, body.mass, body.s, body.J2, body.radius)
        dp_q_eta_tar = dp1_tar * np.cos(theta_target[i]) + dp2_tar * np.sin(theta_target[i])
        
        # sun correction
        dl_sun = deflection_mod3(l0, sun.pos, eps, sun.mass)
        
        t_targ_new = t+(defl_tar + dp1_tar)*n + dp2_tar*m
        t_targ_new = t_targ_new/LA.norm(t_targ_new)
        
        
        ##################
        #
        # print
        #
        ##################
        print(f'\nb_J: {bj_target[i]}')
        print(f'\ndefl_tar: {np.rad2deg(defl_tar)*3600*1e6} muas')
        print(f'dp1_tar: {np.rad2deg(dp1_tar)*3600*1e6} muas')
        print(f'dp2_tar: {np.rad2deg(dp2_tar)*3600*1e6} muas')
        print(f'dp_eta_tar: {np.rad2deg(dp_eta_tar)*3600*1e6} muas')
        print(f'dp_q_eta_tar: {np.rad2deg(dp_q_eta_tar)*3600*1e6} muas\n')
        # print(f'dl_sun: {np.rad2deg(dl_sun)*3600*1e6} muas\n')
        
        
        # loop over reference
        x_ref = np.array([reference_df['starGCdirX'], reference_df['starGCdirY'], reference_df['starGCdirZ']]).T
        for j in range(len(reference_df)):
            
            # direction
            l0 = x_ref[j]
            
            # triplet
            t, n, m = on_triplet(l0, body.pos)
        
            # deflection
            defl_ref = deflection_mod3(l0, body.pos, eps, body.mass)
            dp_eta_ref = defl_ref * np.cos(theta_reference[i])
            
            diff = dp_eta_tar - dp_eta_ref
            
            # deflection quadrupole
            dp1_ref, dp2_ref = deflection_mod3(l0, body.pos, eps, body.mass, body.s, body.J2, body.radius)
            dp_q_eta_ref = dp1_ref * np.cos(theta_reference[j]) + dp2_ref * np.sin(theta_reference[j])
            
            diff_q = dp_q_eta_tar - dp_q_eta_ref
            
            shell_epoch[i, j] = np.rad2deg(diff)*3600*1e6
            shell_q_epoch[i, j] = np.rad2deg(diff_q)*3600*1e6
            
            # sun correction
            dl_sun = deflection_mod3(l0, sun.pos, eps, sun.mass)
            
            t_ref_new = t+(defl_ref + dp1_ref)*n + dp2_ref*m
            t_ref_new = t_ref_new/LA.norm(t_ref_new)
            
            dt_new.append(np.rad2deg(np.arccos(np.dot(t_targ_new, t_ref_new)))*3600*1e6)
            
            ##################
            #
            # print
            #
            ##################
            print(f'\nb_J: {bj_reference[j]}')
            print(f'defl_ref: {np.rad2deg(defl_ref)*3600*1e6} muas')
            print(f'dp1_ref: {np.rad2deg(dp1_ref)*3600*1e6} muas')
            print(f'dp2_ref: {np.rad2deg(dp2_ref)*3600*1e6} muas')
            print(f'dp_eta_ref: {np.rad2deg(dp_eta_ref)*3600*1e6} muas')
            print(f'dp_q_eta_ref: {np.rad2deg(dp_q_eta_ref)*3600*1e6} muas\n')
            # print(f'dl_sun: {np.rad2deg(dl_sun)*3600*1e6} muas\n')
            
    
    shell.append(shell_epoch)
    shell_q.append(shell_q_epoch)


---------- epoch: 2017.1452385988 ----------


b_J: 4.427643850555587

defl_tar: 3818.1267893230747 muas
dp1_tar: 1.2482921122735082 muas
dp2_tar: -2.632888422855534 muas
dp_eta_tar: 2013.735307350294 muas
dp_q_eta_tar: -1.5785560974354929 muas


b_J: 81.58707469920164
defl_ref: 207.1945725642207 muas
dp1_ref: -0.0003935378213349119 muas
dp2_ref: -0.0002471025612450895 muas
dp_eta_ref: -198.63294413282023 muas
dp_q_eta_ref: 0.0004475749590271111 muas


b_J: 108.15506981721754
defl_ref: 156.29905966767274 muas
dp1_ref: -0.00019890231804004096 muas
dp2_ref: 2.454735694175988e-05 muas
dp_eta_ref: -149.84051948251835 muas
dp_q_eta_ref: -0.00019992397350955418 muas


b_J: 20.941452965187587
defl_ref: 807.1988827712722 muas
dp1_ref: -0.015778194978545008 muas
dp2_ref: -0.022545809600284097 muas
dp_eta_ref: -773.8440664795128 muas
dp_q_eta_ref: 0.024512027028917242 muas


b_J: 33.30194388495801
defl_ref: 507.60528378643096 muas
dp1_ref: -0.003323173349347066 muas
dp2_ref: -0.0059914788703127

b_J: 20.943924207029088
defl_ref: 807.1168799696599 muas
dp1_ref: -0.015769884738031925 muas
dp2_ref: -0.022541389498994514 muas
dp_eta_ref: -773.7620597654573 muas
dp_q_eta_ref: 0.02450393871996262 muas


b_J: 33.29967887114859
defl_ref: 507.639576357373 muas
dp1_ref: -0.0033243912710356443 muas
dp2_ref: -0.005992391291657686 muas
dp_eta_ref: -486.66092107441796 muas
dp_q_eta_ref: -0.005934974317279697 muas


b_J: 50.711518449008324
defl_ref: 333.3406740088821 muas
dp1_ref: -0.001852988694822231 muas
dp2_ref: -0.0005789089543074095 muas
dp_eta_ref: -319.5650753016268 muas
dp_q_eta_ref: -0.0019215331972248031 muas


b_J: 31.854371927028204
defl_ref: 530.6775839064288 muas
dp1_ref: 0.005883677391001737 muas
dp2_ref: 0.0051592823084199 muas
dp_eta_ref: -508.7468625488668 muas
dp_q_eta_ref: -0.0026972232915629013 muas


b_J: 58.58782923582608
defl_ref: 288.52731255480563 muas
dp1_ref: -0.0008010588403328613 muas
dp2_ref: 0.000971275707645423 muas
dp_eta_ref: -276.60366571616055 muas
dp_q_

In [19]:
#shell

In [20]:
#shell_q

Create data

In [85]:
# angular separation
data_y = []
for epoch in epochs:
    
    print(f'\n---------- epoch: {epoch} ----------\n')
    
    # take only data for the given epoch
    filt = stars_data['tAFx'] == epoch
    stars_epoch = stars_data.loc[filt]
    
    # split into target and reference
    target_df, reference_df = ref_targ_split(stars_epoch)
    
    theta_target = target_df['theta'].to_numpy()
    theta_reference = reference_df['theta'].to_numpy()
    
    r_p = np.zeros((len(target_df), len(reference_df)))
    r_m = np.zeros((len(target_df), len(reference_df)))
    
    err_r_p = np.zeros((len(target_df), len(reference_df)))
    err_r_m = np.zeros((len(target_df), len(reference_df)))
    
    eta_targ = target_df['etaS[deg]'].to_numpy()
    eta_ref = reference_df['etaS[deg]'].to_numpy()
    
    zeta_targ = target_df['zetaS[deg]'].to_numpy()
    zeta_ref = reference_df['zetaS[deg]'].to_numpy()
    
    err_eta_targ = target_df['sig_eta[mas]'].to_numpy() * 1e3
    err_eta_ref = reference_df['sig_eta[mas]'].to_numpy() * 1e3
    
    err_zeta_targ = target_df['sig_zeta[mas]'].to_numpy() * 1e3
    err_zeta_ref = reference_df['sig_zeta[mas]'].to_numpy() * 1e3
    
    x_targ = target_df['starGCdirX'].to_numpy()
    y_targ = target_df['starGCdirY'].to_numpy()
    z_targ = target_df['starGCdirZ'].to_numpy()
    
    x_ref = reference_df['starGCdirX'].to_numpy()
    y_ref = reference_df['starGCdirY'].to_numpy()
    z_ref = reference_df['starGCdirZ'].to_numpy()
    
    alpha_targ = target_df['starRA[deg]_new'].to_numpy() + target_df['dRA[deg]'].to_numpy()
    delta_targ = target_df['starDec[deg]_new'].to_numpy() + target_df['dDEC[deg]'].to_numpy()
    alpha_ref =  reference_df['starRA[deg]_new'].to_numpy() +  reference_df['dRA[deg]'].to_numpy()
    delta_ref = reference_df['starDec[deg]_new'].to_numpy() +  reference_df['dDEC[deg]'].to_numpy()
    
    jup_epoch = np.array([stars_epoch['jupPosGCX[m]'], stars_epoch['jupPosGCY[m]'], stars_epoch['jupPosGCZ[m]']]).T
    jup_epoch = jup_epoch[0]
    jup_epoch = jup_epoch/LA.norm(jup_epoch)
    
    alpha_jup = stars_epoch['long_jupGC[deg]'].to_numpy()[0]
    delta_jup = stars_epoch['lat_jupGC[deg]'].to_numpy()[0]
    
    eta_J_tar = target_df['etaJup[deg]'].to_numpy()
    zeta_J_tar = target_df['zetaJup[deg]'].to_numpy()
    
    eta_J_ref = reference_df['etaJup[deg]'].to_numpy()
    zeta_J_ref = reference_df['zetaJup[deg]'].to_numpy()
    
    # loop over target
    for i in range(len(target_df)):
        
        r_targ = np.array([x_targ[i], y_targ[i], z_targ[i]]) 
        
        chi_targ = np.arccos(np.dot(r_targ, jup_epoch))
        chi_targ_eta = chi_targ*np.cos(theta_target[i])
        #print(f'chi_targ:       {chi_targ}')
        #print(f'chi_targ_eta:   {chi_targ_eta}')
        
        eta_rel_targ = eta_targ[i] - eta_J_tar[i]
        zeta_rel_targ = zeta_targ[i] - zeta_J_tar[i]
        
        alpha_rel_targ = alpha_targ[i] - alpha_jup
        delta_rel_targ = delta_targ[i] - delta_jup
        
        
        # a_targ_new = np.deg2rad(np.sqrt(eta_rel_targ**2 + zeta_rel_targ**2))
        a_targ_new = np.arccos(np.dot(cartesian(eta_targ[i], zeta_targ[i]), cartesian(eta_J_tar[i], zeta_J_tar[i])))
        #a_targ = np.deg2rad(np.sqrt(alpha_rel_targ**2 + delta_rel_targ**2))
        a_targ = chi_targ
        print(np.rad2deg(a_targ_new)*3600e6 - np.rad2deg(a_targ)*3600e6)
        
        
        # loop over reference
        for j in range(len(reference_df)):
            
            r_ref = np.array([x_ref[j], y_ref[j], z_ref[j]])
            
            theta_rel = np.arctan(np.abs((zeta_ref[j] - zeta_targ[i]) /  (eta_ref[j] - eta_targ[i])))

            
            chi_ref = np.arccos(np.dot(r_ref, jup_epoch))
            chi_ref_eta = chi_ref*np.cos(theta_reference[j])
            
            #print(f'chi_ref:      {chi_ref}')
            #print(f'chi_ref_eta:  {chi_ref_eta}')
            

            #r_p[i, j] = np.sqrt((eta_targ[i] - eta_ref[j])**2 + (zeta_targ[i] - zeta_ref[j])**2)*3600*1e6
            #r_p[i, j] = np.abs((eta_targ[i] - eta_ref[j])) *3600*1e6
            
            
            #r_p[i, j] = np.rad2deg(np.arccos(np.dot(cartesian(eta_targ[i], zeta_targ[i]), cartesian(eta_ref[j], zeta_ref[j]))))*3600*1e6
            #r_m[i, j] = np.rad2deg(np.arccos(np.dot(r_targ, r_ref))) *3600*1e6 #* np.cos(theta_rel)
            
            # r_m [i, j] = np.sqrt((alpha_targ[i] - alpha_ref[j])**2 + (delta_targ[i] - delta_ref[j])**2)*3600*1e6
            #r_m[i, j] = chi_ref_eta + chi_targ_eta
            
            
            eta_rel_ref = eta_ref[j] - eta_J_ref[j]
            zeta_rel_ref = zeta_ref[j] - zeta_J_ref[j]
        
            alpha_rel_ref = alpha_ref[j] - alpha_jup
            delta_rel_ref = delta_ref[j] - delta_jup
        
            #a_ref_new = np.deg2rad(np.sqrt(eta_rel_ref**2 + zeta_rel_ref**2))
            a_ref_new = np.arccos(np.dot(cartesian(eta_ref[j], zeta_ref[j]), cartesian(eta_J_ref[j], zeta_J_ref[j])))
            #a_ref = np.deg2rad(np.sqrt(alpha_rel_ref**2 + delta_rel_ref**2))
            a_ref = chi_ref
            print(np.rad2deg(a_ref_new)*3600e6 - np.rad2deg(a_ref)*3600e6)
            
            
            r_p[i, j] = np.rad2deg((np.cos(a_targ_new) - np.cos(a_targ))/np.sin(a_targ))*3600e6
            r_m[i, j] = np.rad2deg((np.cos(a_ref_new) - np.cos(a_ref))/np.sin(a_ref))*3600e6
            
            
            
            err_r_p[i, j] = LA.norm([err_eta_targ[i], err_eta_ref[j]])
            
            print(f'sep_j: {r_p[i, j]} muas')
            print(f'sep:   {r_m[i, j]} muas\n')
            # print(f'err: {err_r_p[i, j]} muas\n')
            
            
            
             
                
    data_y.append(np.abs(r_p - r_m ))



---------- epoch: 2017.1452385988 ----------

-369.8095567971468
-87804.44500303268
sep_j: 369.80878461830076 muas
sep:   87802.08278620169 muas

-88214.1152100563
sep_j: 369.80878461830076 muas
sep:   88212.31660529028 muas

-36131.45287781954
sep_j: 369.80878461830076 muas
sep:   36129.894523797804 muas

-44198.2729203701
sep_j: 369.80878461830076 muas
sep:   44196.80652626541 muas

-69898.57918083668
sep_j: 369.80878461830076 muas
sep:   69896.17080471842 muas

-95349.23137712479
sep_j: 369.80878461830076 muas
sep:   95347.17356355493 muas

-48555.793892383575
sep_j: 369.80878461830076 muas
sep:   48553.943549577365 muas

-80834.79198670387
sep_j: 369.80878461830076 muas
sep:   80832.00397289447 muas

-28478.346463620663
sep_j: 369.80878461830076 muas
sep:   28477.326584342798 muas

-62418.28912162781
sep_j: 369.80878461830076 muas
sep:   62416.00692467463 muas

-58331.58797669411
sep_j: 369.80878461830076 muas
sep:   58329.43283548422 muas

-28357.29459810257
sep_j: 369.8087846183

In [82]:
data_y

[array([[87432.27400158338 , 87842.50782067198 , 35760.0857391795  ,
         43826.99774164711 , 69526.36202010012 , 94977.36477893662 ,
         48184.13476495906 , 80462.19518827616 , 28107.517799724497,
         62046.19814005632 , 57959.62405086592 , 27986.533542343197,
         26593.104370571997, 78652.4290925709  , 40161.46448378496 ]]),
 array([[90562.19768228167 , 88040.1685155476  , 35064.28350546594 ,
         43471.76665664263 , 69941.73423558251 , 92865.94341534998 ,
         48891.042264264346, 80017.84905351329 , 25373.62057529196 ,
         57485.838954400024, 54646.73882791275 , 29267.896248594305,
         26038.689029066685, 79037.74531241921 , 41171.99899265839 ]]),
 array([[93095.24417111262 , 90204.9435223146  , 32332.104361391277,
         45366.263505084105, 71624.82697804536 , 94948.56266885798 ,
         52122.65844182961 , 82310.78064685353 , 26765.913266578318,
         56507.963316275825, 56862.51282582743 , 31303.135752776543,
         28377.18462844089 ,

In [23]:
conv = 1e-6/pc
x_test_s = cartesian(stars_data['starRA[deg]'], stars_data['starDec[deg]']).T
par = stars_data['parallax[mas]'].to_numpy() * conv
x_test_s = np.array([x_test_s[i]*(1/par[i]) for i in range(len(par))])

In [24]:
x_gaia = np.array([stars_data['gaiaPosX[m]'], stars_data['gaiaPosY[m]'], stars_data['gaiaPosZ[m]']]).T
x_s_GC = x_test_s - x_gaia

In [25]:
x_s_GC_n = np.linalg.norm(x_s_GC, axis=1)
for i in range(len(x_s_GC)):
    print(x_s_GC[i]/x_s_GC_n[i])

[-0.9214043052868125  -0.36393159456468027 -0.13626408432354978]
[-0.9241111718940843  -0.3633372096341643  -0.11834109208470911]
[-0.9225828691221889  -0.3630520857591138  -0.13051449202378737]
[-0.9240704342155827  -0.3608680406623014  -0.12596860655407793]
[-0.9239857368449542  -0.36179777605462515 -0.12390612312962657]
[-0.9230789168676675  -0.36585521137984095 -0.11863927486556017]
[-0.9222129300578042  -0.3650052467429338  -0.12764983934314025]
[-0.9233031401324711 -0.3619376259516455 -0.1285008417949288]
[-0.9228584994264368  -0.36475686184345407 -0.1236309903482972 ]
[-0.9236480630635924  -0.3606466489889742  -0.12964663579089825]
[-0.9218292427336883  -0.3644252955750325  -0.13200398170542046]
[-0.9224548069178967 -0.3626685019176736 -0.1324714569666093]
[-0.9237219884372454  -0.3614124309099047  -0.12695961114202683]
[-0.9231373726598383  -0.36283995069032365 -0.12713992835350432]
[-0.9222858822683673  -0.36234254345416567 -0.13452372493960094]
[-0.9224906063954232  -0.363119

In [26]:
np.array([stars_data['starGCdirX'], stars_data['starGCdirY'], stars_data['starGCdirZ']]).T[0]

array([-0.921404405408743  , -0.36393129501790583, -0.13626420733248587])

## Non linear fit

In [27]:
from scipy.optimize import curve_fit

In [28]:
def model(x_data, gamma, epsilon):
    
    dpsi_mono = x_data[0]
    dpsi_quad = x_data[1]
    
    dr = (1+gamma)*(dpsi_mono + epsilon*dpsi_quad)
    
    return dr

In [29]:
shell = [ep.squeeze() for ep in shell]
shell = np.concatenate(shell)

shell_q = [ep.squeeze() for ep in shell_q]
shell_q = np.concatenate(shell_q)

data_y = [ep.squeeze() for ep in data_y]
data_y = np.concatenate(data_y)

In [30]:
xdata = np.array([shell/2, shell_q/2]).squeeze()
ydata = np.array(data_y).squeeze()
ydata

array([87702.70594501495 , 87776.16280841827 , 37172.18825483322 ,
       43856.33403098583 , 69116.75989174843 , 94479.31328821182 ,
       48289.88124525547 , 80333.93963313103 , 28491.5924153924  ,
       62869.88188076019 , 59392.56638836861 , 28067.114919364452,
       27699.16510552168 , 79044.44870114326 , 41179.74205267429 ,
       90673.95980334282 , 86493.68043589592 , 35542.914988934994,
       42944.42214536667 , 68542.61462259293 , 90441.80044937134 ,
       47067.993972182274, 78012.81495928764 , 26997.46836209297 ,
       57171.92704319954 , 54198.08866691589 , 28423.55069589615 ,
       24383.58119338751 , 79308.54590988159 , 41598.79574179649 ,
       90284.05870485306 , 86761.51849389076 , 28589.852193892002,
       44107.55418241024 , 68801.98452138901 , 90046.07554197311 ,
       46347.246462106705, 77617.78250932693 , 27783.893871307373,
       52437.37112188339 , 53631.478122234344, 29600.49832522869 ,
       24120.279978454113, 79352.29026532173 , 32028.907665967

In [31]:
rng = np.random.default_rng()
y_noise = 0.05 * rng.normal(size=xdata.shape[1])
ydata = np.array(shell) + np.array(shell_q) +y_noise
ydata = ydata.squeeze()
ydata

array([2210.79863192163  , 2161.9223986512748, 2785.9923099615844,
       2498.715604483828 , 2331.71748577925  , 2158.9003698699744,
       2520.9623600819787, 2288.7339100966783, 2827.351406183225 ,
       2391.802755698639 , 2422.776971403175 , 2779.830470003771 ,
       2942.394861223814 , 2280.371305886707 , 2642.469973822287 ,
       2211.053736990781 , 2162.2725659787966, 2786.1851603842124,
       2499.069932248351 , 2332.041641730706 , 2159.1014252659643,
       2521.139357446382 , 2289.0798471276885, 2827.617805703687 ,
       2392.2055958783676, 2422.9861694670153, 2780.1258043227585,
       2942.5685251534214, 2280.563470291586 , 2642.6867001979376,
       2211.2650373105726, 2162.46919028073  , 2786.5111459316695,
       2499.2899092374214, 2332.2315085186583, 2159.338274824953 ,
       2521.4487881408845, 2289.337619508241 , 2827.880456779669 ,
       2392.4477175989987, 2423.289724930797 , 2780.4011989106853,
       2942.854176216492 , 2280.857928127057 , 2642.9529998771

In [32]:
# constrain optimization
popt, pcov = curve_fit(model, xdata, ydata, p0=(1,0), bounds=(0, [10, 10]))

In [33]:
popt

array([0.9999726748305101, 0.9862091025382914])

In [34]:
data_y

array([87702.70594501495 , 87776.16280841827 , 37172.18825483322 ,
       43856.33403098583 , 69116.75989174843 , 94479.31328821182 ,
       48289.88124525547 , 80333.93963313103 , 28491.5924153924  ,
       62869.88188076019 , 59392.56638836861 , 28067.114919364452,
       27699.16510552168 , 79044.44870114326 , 41179.74205267429 ,
       90673.95980334282 , 86493.68043589592 , 35542.914988934994,
       42944.42214536667 , 68542.61462259293 , 90441.80044937134 ,
       47067.993972182274, 78012.81495928764 , 26997.46836209297 ,
       57171.92704319954 , 54198.08866691589 , 28423.55069589615 ,
       24383.58119338751 , 79308.54590988159 , 41598.79574179649 ,
       90284.05870485306 , 86761.51849389076 , 28589.852193892002,
       44107.55418241024 , 68801.98452138901 , 90046.07554197311 ,
       46347.246462106705, 77617.78250932693 , 27783.893871307373,
       52437.37112188339 , 53631.478122234344, 29600.49832522869 ,
       24120.279978454113, 79352.29026532173 , 32028.907665967