# Compound shell

## Import packages

In [1]:
import pandas as pd
import numpy as np
from astropy import constants
from astronavigation.deflection import *
from astronavigation.planets import Body, SolarSystem

## Useful constants

In [110]:
pc = constants.pc.to('km').value
AU = constants.au.to('km').value
c = constants.c.to('km/s').value
eps = 1/c

v_null = np.array([0, 0, 0])

# Create Solar System
ss = SolarSystem()

jupiter = ss.getPlanet('jupiter')
r_jup_arc = 20  # mean jupiter radius in arcseconds

## Read and clean data

Read data

In [111]:
# path
path = 'Stars_GareqEvent2017_oneTransit_new2.dat'

# read, use delimiter='\s+' to choose every white space as delimiter
stars_data = pd.read_table(path, delimiter='\s+')

# display
pd.set_option('display.max_columns', None)
stars_data.head(10)

tAF5         tAFx               starId     etaS[deg]  sig_eta[mas]  \
0  2017.145239  2017.145239  3631075715518049024  4.475043e-01      0.099969   
1  2017.145239  2017.145239  3631485528413582336 -5.870432e-01      0.072845   
2  2017.145239  2017.145239  3631191099815174272  1.157136e-01      0.091820   
3  2017.145239  2017.145239  3631256894418771584 -1.456322e-01      0.096824   
4  2017.145239  2017.145239  3631266072764288000 -2.651681e-01      0.103025   
5  2017.145239  2017.145239  3631298199119733504 -5.711045e-01      0.076116   
6  2017.145239  2017.145239  3631241265033227392 -5.069712e-02      0.074388   
7  2017.145239  2017.145239  3631239925003381248 -1.514225e-07      0.100975   
8  2017.145239  2017.145239  3631255107712373376 -2.825577e-01      0.065251   
9  2017.145239  2017.145239  3631145740665759616  6.684247e-02      0.093621   

   zetaS[deg]  sig_zeta[mas]  etaJup[deg]  zetaJup[deg]  etaSpin[deg]  \
0    0.149847       0.372775     0.012973      0.020895     20.471557   
1    0.052752       0.312333     0.012973      0.020895     20.471557   
2    0.075482       0.339177     0.012973      0.020895     20.471557   
3   -0.074359       0.311625     0.012973      0.020895     20.471557   
4   -0.023983       0.389037     0.012973      0.020895     20.471557   
5    0.208823       0.297541     0.012973      0.020895     20.471557   
6    0.185999       0.254893     0.012973      0.020895     20.471557   
7   -0.000004       0.368185     0.012973      0.020895     20.471557   
8    0.157291       0.272657     0.012973      0.020895     20.471557   
9   -0.075513       0.311841     0.012973      0.020895     20.471557   

   zetaSpin[deg]  jupPosGCX[m]  jupPosGCY[m]  jupPosGCZ[m]   gaiaPosX[m]  \
0      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
1      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
2      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
3      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
4      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
5      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
6      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
7      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
8      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
9      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   

    gaiaPosY[m]   gaiaPosZ[m]  long_jupGC[deg]  lat_jupGC[deg]  \
0  6.053463e+10  2.630360e+10       201.426291       -7.396121   
1  6.053463e+10  2.630360e+10       201.426291       -7.396121   
2  6.053463e+10  2.630360e+10       201.426291       -7.396121   
3  6.053463e+10  2.630360e+10       201.426291       -7.396121   
4  6.053463e+10  2.630360e+10       201.426291       -7.396121   
5  6.053463e+10  2.630360e+10       201.426291       -7.396121   
6  6.053463e+10  2.630360e+10       201.426291       -7.396121   
7  6.053463e+10  2.630360e+10       201.426291       -7.396121   
8  6.053463e+10  2.630360e+10       201.426291       -7.396121   
9  6.053463e+10  2.630360e+10       201.426291       -7.396121   

   long_gaia[deg]  lat_gaia[deg]  starRA[deg]  starDec[deg]  
0       155.66443      10.151667   201.552776     -7.831722  
1       155.66443      10.151667   201.463499     -6.796371  
2       155.66443      10.151667   201.480483     -7.499324  
3       155.66443      10.151667   201.331641     -7.236695  
4       155.66443      10.151667   201.383427     -7.117590  
5       155.66443      10.151667   201.620517     -6.813578  
6       155.66443      10.151667   201.593303     -7.333806  
7       155.66443      10.151667   201.405330     -7.382970  
8       155.66443      10.151667   201.566250     -7.101704  
9       155.66443      10.151667   201.328604     -7.449173

Create queary for source_id and add parallaxes to the data

In [112]:
# not need to evaluate this cell if new data has been already downloaded
with open('query.txt', 'w') as f:
    
    star_id = stars_data['starId'].unique()
    query = 'SELECT *\nFROM gaiaedr3.gaia_source\nWHERE '
    
    for id in star_id:
        query += f'source_id = {id} '
        if id != star_id[-1]:
            query += 'OR '
    f.write(query)

In [113]:
# parallax and parallax erro are in mas
new_data = pd.read_csv('1654093971685O-result.csv')
new_data = new_data[['source_id', 'parallax', 'parallax_error']]
new_data = new_data.set_index('source_id')
new_data

parallax  parallax_error
source_id                                     
3631075715518049024   3.409062        0.032620
3631089188831339264   5.459490        0.035637
3631095407943986048   0.243898        0.018328
3631096438736162944   0.535781        0.026916
3631145740665759616   1.217448        0.033738
3631186628753669888   0.400931        0.014865
3631191099815174272   1.352386        0.018157
3631239925003381248   0.472181        0.016357
3631241265033227392   0.758436        0.020345
3631244559272698112   0.488491        0.018010
3631244937229820800   2.545210        0.030274
3631255107712373376   3.914919        0.023334
3631256894418771584   6.970485        0.017854
3631266072764288000   1.330410        0.015664
3631298199119733504   1.593033        0.015341
3631485528413582336  10.354598        0.184979

In [114]:
# add parallax
parallax = []
parallax_err = []
for id in stars_data['starId']:
    p = new_data['parallax']
    err = new_data['parallax_error']
    parallax.append(p.loc[id])
    parallax_err.append(err.loc[id])
stars_data['parallax[mas]'] = parallax
stars_data['parallax_err[mas]'] = parallax_err
stars_data

tAF5         tAFx               starId  etaS[deg]  sig_eta[mas]  \
0    2017.145239  2017.145239  3631075715518049024   0.447504      0.099969   
1    2017.145239  2017.145239  3631485528413582336  -0.587043      0.072845   
2    2017.145239  2017.145239  3631191099815174272   0.115714      0.091820   
3    2017.145239  2017.145239  3631256894418771584  -0.145632      0.096824   
4    2017.145239  2017.145239  3631266072764288000  -0.265168      0.103025   
..           ...          ...                  ...        ...           ...   
137  2017.145239  2017.145240  3631095407943986048   0.228960      0.071818   
138  2017.145239  2017.145240  3631244559272698112  -0.088713      0.049222   
139  2017.145239  2017.145240  3631244937229820800  -0.079046      0.054070   
140  2017.145239  2017.145240  3631089188831339264   0.347718      0.055859   
141  2017.145239  2017.145240  3631096438736162944   0.142424      0.046130   

     zetaS[deg]  sig_zeta[mas]  etaJup[deg]  zetaJup[deg]  etaSpin[deg]  \
0      0.149847       0.372775     0.012973      0.020895     20.471557   
1      0.052752       0.312333     0.012973      0.020895     20.471557   
2      0.075482       0.339177     0.012973      0.020895     20.471557   
3     -0.074359       0.311625     0.012973      0.020895     20.471557   
4     -0.023983       0.389037     0.012973      0.020895     20.471557   
..          ...            ...          ...           ...           ...   
137    0.058662       0.318960     0.012963      0.020873     19.823930   
138   -0.037527       0.220813     0.012963      0.020873     19.823930   
139    0.050917       0.226070     0.012963      0.020873     19.823930   
140    0.045807       0.233511     0.012963      0.020873     19.823930   
141    0.081247       0.184189     0.012963      0.020873     19.823930   

     zetaSpin[deg]  jupPosGCX[m]  jupPosGCY[m]  jupPosGCZ[m]   gaiaPosX[m]  \
0        22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
1        22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
2        22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
3        22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
4        22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
..             ...           ...           ...           ...           ...   
137      22.785597 -6.550931e+11 -2.570747e+11 -9.134985e+10 -1.338483e+11   
138      22.785597 -6.550931e+11 -2.570747e+11 -9.134985e+10 -1.338483e+11   
139      22.785597 -6.550931e+11 -2.570747e+11 -9.134985e+10 -1.338483e+11   
140      22.785597 -6.550931e+11 -2.570747e+11 -9.134985e+10 -1.338483e+11   
141      22.785597 -6.550931e+11 -2.570747e+11 -9.134985e+10 -1.338483e+11   

      gaiaPosY[m]   gaiaPosZ[m]  long_jupGC[deg]  lat_jupGC[deg]  \
0    6.053463e+10  2.630360e+10       201.426291       -7.396121   
1    6.053463e+10  2.630360e+10       201.426291       -7.396121   
2    6.053463e+10  2.630360e+10       201.426291       -7.396121   
3    6.053463e+10  2.630360e+10       201.426291       -7.396121   
4    6.053463e+10  2.630360e+10       201.426291       -7.396121   
..            ...           ...              ...             ...   
137  6.053366e+10  2.630318e+10       201.426269       -7.396111   
138  6.053366e+10  2.630318e+10       201.426269       -7.396111   
139  6.053366e+10  2.630318e+10       201.426269       -7.396111   
140  6.053366e+10  2.630318e+10       201.426269       -7.396111   
141  6.053366e+10  2.630318e+10       201.426269       -7.396111   

     long_gaia[deg]  lat_gaia[deg]  starRA[deg]  starDec[deg]  parallax[mas]  \
0        155.664430      10.151667   201.552776     -7.831722       3.409062   
1        155.664430      10.151667   201.463499     -6.796371      10.354598   
2        155.664430      10.151667   201.480483     -7.499324       1.352386   
3        155.664430      10.151667   201.331641     -7.236695       6.970485   
4       

Evaluate impact parameter

In [115]:
# star and jupiter coordinates
star = np.array([stars_data['etaS[deg]'], stars_data['zetaS[deg]']])
jup = np.array([stars_data['etaJup[deg]'], stars_data['zetaJup[deg]']])

# impact parameter in units of jupiter radius
stars_data['b_J'] = np.linalg.norm(star - jup, axis=0) * 3600 / r_jup_arc 

Evaluate parallax displacement

In [116]:
# need to transform mas to m^-1
conv = 1e-6/pc  # 1e-3/(pc*1e3)
# useful quantities
alpha = np.deg2rad(stars_data['starRA[deg]'])
delta = np.deg2rad(stars_data['starDec[deg]'])
X = stars_data['gaiaPosX[m]']
Y = stars_data['gaiaPosY[m]']
Z = stars_data['gaiaPosZ[m]']
omega = stars_data['parallax[mas]']

d_alpha = omega*(1/np.cos(delta))*(X*np.sin(alpha) - Y*np.cos(alpha)) * conv
d_delta = omega*(X*np.cos(alpha)*np.sin(delta) +Y*np.sin(alpha)*np.sin(delta) - Z*np.cos(delta)) * conv

star_gaia_dir = np.array([np.cos(alpha + d_alpha)*np.cos(delta + d_delta), np.sin(alpha + d_alpha)*np.cos(delta + d_delta), np.sin(delta + d_delta)])
star_gaia_dir = star_gaia_dir

In [117]:
# add star_gaia_dir
stars_data['starGCdirX'] = star_gaia_dir[0]
stars_data['starGCdirY'] = star_gaia_dir[1]
stars_data['starGCdirZ'] = star_gaia_dir[2]

In [118]:
# evaluate jupiter direction

jup_gaia_dir = cartesian(stars_data['long_jupGC[deg]'], stars_data['lat_jupGC[deg]'])
jup_gaia_dir.T

array([[-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.92314318, -0.3622646 , -0.12872846],
       [-0.9231432 , -0.36226456, -0.12872844],
       [-0.9231432 , -0.36226456, -0.12872844],
       [-0.9231432 , -0.36226456, -0.12872844],
       [-0.9231432 , -0.36226456, -0.12872844],
       [-0.9231432 , -0.36226456, -0.128

In [119]:
# check results
jp = np.array([stars_data['jupPosGCX[m]'], stars_data['jupPosGCY[m]'], stars_data['jupPosGCZ[m]']]).T
jp_n = np.linalg.norm(jp, axis=1)

for i in range(len(jp)):
    print(jp[i]/jp_n[i])

[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.92314318 -0.3622646  -0.12872846]
[-0.9231432  -0.36226456 -0.12872844]
[-0.9231432  -0.36226456 -0.12872844]
[-0.9231432  -0.36226456 -0.12872844]
[-0.9231432  -0.36226456 -0.12872844]
[-0.9231432  -0.36226456 -0.12872844]
[-0.9231432  -0.36226456 -0.12872844]
[-0.9231432  -0.36226456 -0.12872844]
[-0.9231432  -0.36226456 -0.12872844]
[-0.9231432  -0.36226456 -0.12872844]
[-0.9231432  -0.36226456 -0.12872844]
[-0.9231432 

Evaluate theta

In [120]:
# useful values
eta_s = np.deg2rad(stars_data['etaS[deg]'])
zeta_s = np.deg2rad(stars_data['zetaS[deg]'])
eta_J = np.deg2rad(stars_data['etaJup[deg]'])
zeta_J = np.deg2rad(stars_data['zetaJup[deg]'])

# gnomonic coordinates
# cos_psi = np.sin(zeta_J)*np.sin(zeta_s) + np.cos(zeta_J)*np.cos(zeta_s)*np.cos(eta_J - eta_s)
# the previous factor can be neglected because we take the fraction
y_g = np.cos(zeta_J)*np.sin(eta_J - eta_s)
x_g = np.sin(zeta_J)*np.sin(zeta_s) - np.cos(zeta_J)*np.cos(zeta_s)*np.cos(eta_J - eta_s)
theta = np.arctan(np.abs(y_g/x_g))
stars_data['theta'] = theta

In [121]:
theta

0      0.007584
1      0.010472
2      0.001793
3      0.002768
4      0.004854
         ...   
137    0.003770
138    0.001775
139    0.001606
140    0.005843
141    0.002260
Length: 142, dtype: float64

In [122]:
#stars_data['theta']=np.arctan(np.abs((stars_data['zetaS[deg]'] - stars_data['zetaJup[deg]'])
#                                         / (stars_data['etaS[deg]'] - stars_data['etaJup[deg]'])))

Display data

In [123]:
stars_data.head(10)

tAF5         tAFx               starId     etaS[deg]  sig_eta[mas]  \
0  2017.145239  2017.145239  3631075715518049024  4.475043e-01      0.099969   
1  2017.145239  2017.145239  3631485528413582336 -5.870432e-01      0.072845   
2  2017.145239  2017.145239  3631191099815174272  1.157136e-01      0.091820   
3  2017.145239  2017.145239  3631256894418771584 -1.456322e-01      0.096824   
4  2017.145239  2017.145239  3631266072764288000 -2.651681e-01      0.103025   
5  2017.145239  2017.145239  3631298199119733504 -5.711045e-01      0.076116   
6  2017.145239  2017.145239  3631241265033227392 -5.069712e-02      0.074388   
7  2017.145239  2017.145239  3631239925003381248 -1.514225e-07      0.100975   
8  2017.145239  2017.145239  3631255107712373376 -2.825577e-01      0.065251   
9  2017.145239  2017.145239  3631145740665759616  6.684247e-02      0.093621   

   zetaS[deg]  sig_zeta[mas]  etaJup[deg]  zetaJup[deg]  etaSpin[deg]  \
0    0.149847       0.372775     0.012973      0.020895     20.471557   
1    0.052752       0.312333     0.012973      0.020895     20.471557   
2    0.075482       0.339177     0.012973      0.020895     20.471557   
3   -0.074359       0.311625     0.012973      0.020895     20.471557   
4   -0.023983       0.389037     0.012973      0.020895     20.471557   
5    0.208823       0.297541     0.012973      0.020895     20.471557   
6    0.185999       0.254893     0.012973      0.020895     20.471557   
7   -0.000004       0.368185     0.012973      0.020895     20.471557   
8    0.157291       0.272657     0.012973      0.020895     20.471557   
9   -0.075513       0.311841     0.012973      0.020895     20.471557   

   zetaSpin[deg]  jupPosGCX[m]  jupPosGCY[m]  jupPosGCZ[m]   gaiaPosX[m]  \
0      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
1      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
2      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
3      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
4      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
5      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
6      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
7      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
8      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   
9      22.787461 -6.550938e+11 -2.570753e+11 -9.135009e+10 -1.338477e+11   

    gaiaPosY[m]   gaiaPosZ[m]  long_jupGC[deg]  lat_jupGC[deg]  \
0  6.053463e+10  2.630360e+10       201.426291       -7.396121   
1  6.053463e+10  2.630360e+10       201.426291       -7.396121   
2  6.053463e+10  2.630360e+10       201.426291       -7.396121   
3  6.053463e+10  2.630360e+10       201.426291       -7.396121   
4  6.053463e+10  2.630360e+10       201.426291       -7.396121   
5  6.053463e+10  2.630360e+10       201.426291       -7.396121   
6  6.053463e+10  2.630360e+10       201.426291       -7.396121   
7  6.053463e+10  2.630360e+10       201.426291       -7.396121   
8  6.053463e+10  2.630360e+10       201.426291       -7.396121   
9  6.053463e+10  2.630360e+10       201.426291       -7.396121   

   long_gaia[deg]  lat_gaia[deg]  starRA[deg]  starDec[deg]  parallax[mas]  \
0       155.66443      10.151667   201.552776     -7.831722       3.409062   
1       155.66443      10.151667   201.463499     -6.796371      10.354598   
2       155.66443      10.151667   201.480483     -7.499324       1.352386   
3       155.66443      10.151667   201.331641     -7.236695       6.970485   
4       155.66443      10.151667   201.383427     -7.117590       1.330410   
5       155.66443      10.151667   201.620517     -6.813578       1.593033   
6       155.66443      10.151667   201.593303     -7.333806       0.758436   
7       155.66443      10.151667   201.405330     -7.382970       0.472181   
8       155.66443      10.151667   201.566250     -7.101704

### Find target stars

In [124]:
# threshold
thr = 5

# create threshold column
stars_data['thr'] = stars_data['b_J'] <= thr

# print number of targets
stars_data['thr'].value_counts()

False    133
True       9
Name: thr, dtype: int64

### Create target and reference dataframe

In [125]:
def ref_targ_split(df):
    
    filt = df['thr']

    target_df = df.loc[filt]
    reference_df = df.loc[(~filt)]
    
    return target_df, reference_df

## Evaluate deflection

In [126]:
# the positions are Gaiacentric thus we put the observer in the origin


In [127]:
# define epochs
epochs = stars_data['tAFx'].unique()

In [128]:
# differences
shell=[]
shell_q=[]

# loop over epochs
for epoch in epochs:
    
    # take only data for the given epoch
    filt = stars_data['tAFx'] == epoch
    stars_epoch = stars_data.loc[filt]
    
    # split into target and reference
    target_df, reference_df = ref_targ_split(stars_epoch)
    
    theta_target = target_df['theta'].to_numpy()
    theta_reference = reference_df['theta'].to_numpy()
    
    bj_target = target_df['b_J'].to_numpy()
    bj_reference = reference_df['b_J'].to_numpy()
    
    
    shell_epoch = np.zeros((len(target_df), len(reference_df)))
    shell_q_epoch = np.zeros((len(target_df), len(reference_df)))
    
    # Gaia position
    # x_obs = np.array([stars_epoch['gaiaPosX[m]'], stars_epoch['gaiaPosY[m]'], stars_epoch['gaiaPosZ[m]']]).T / 1000 # in km

    # create body
    x_b = np.array([stars_epoch['jupPosGCX[m]'], stars_epoch['jupPosGCY[m]'], stars_epoch['jupPosGCZ[m]']]).T / 1000# in km
    
    # spin = cartesian(stars_epoch['etaSpin[deg]'].iloc[0], stars_epoch['zetaSpin[deg]'].iloc[0])
    
    body = Body(mass=jupiter.mass,
                pos=x_b[0],
                radius=jupiter.radius,
                J2=jupiter.J2,
                s=np.array([0, 0, 1])) 
    
    ##################
    #
    # print
    #
    ##################
    print(f'\n---------- epoch: {epoch} ----------\n')
    
    # loop over target
    x_targ = np.array([target_df['starGCdirX'], target_df['starGCdirY'], target_df['starGCdirZ']]).T
    for i in range(len(target_df)):
        
        # direction
        l0 = x_targ[i]
        
        # deflection
        dl = deflection_mod3(l0, body.pos, eps, body.mass)
        defl_tar = np.linalg.norm(dl)
        dp_eta_tar = defl_tar * np.cos(theta_target[i])
        
       
        # deflection quadrupole
        dp1_tar, dp2_tar = dl = deflection_mod3(l0, body.pos, eps, body.mass, body.s, body.J2, body.radius)
        dp_q_eta_tar = dp1_tar * np.cos(theta_target[i]) + dp2_tar * np.sin(theta_target[i])
        
        
        ##################
        #
        # print
        #
        ##################
        print(f'\nb_J: {bj_target[i]}')
        print(f'\ndefl_tar: {np.rad2deg(defl_tar)*3600*1e6} muas')
        print(f'dp1_tar: {np.rad2deg(dp1_tar)*3600*1e6} muas')
        print(f'dp2_tar: {np.rad2deg(dp2_tar)*3600*1e6} muas')
        print(f'dp_eta_tar: {np.rad2deg(dp_eta_tar)*3600*1e6} muas')
        print(f'dp_q_eta_tar: {np.rad2deg(dp_q_eta_tar)*3600*1e6} muas\n')
        
        
        # loop over reference
        x_ref = np.array([reference_df['starGCdirX'], reference_df['starGCdirY'], reference_df['starGCdirZ']]).T
        for j in range(len(reference_df)):
            
            # direction
            l0 = x_ref[j]
        
            # deflection
            dl = deflection_mod3(l0, body.pos, eps, body.mass)
            defl_ref = np.linalg.norm(dl)
            dp_eta_ref = defl_ref * np.cos(theta_reference[i])
            
            diff = dp_eta_tar - dp_eta_ref
            
            # deflection quadrupole
            dp1_ref, dp2_ref = deflection_mod3(l0, body.pos, eps, body.mass, body.s, body.J2, body.radius)
            dp_q_eta_ref = dp1_ref * np.cos(theta_reference[j]) + dp2_ref * np.sin(theta_reference[j])
            
            diff_q = dp_q_eta_tar - dp_q_eta_ref
            
            shell_epoch[i, j] = np.rad2deg(diff)*3600*1e6
            shell_q_epoch[i, j] = np.rad2deg(diff_q)*3600*1e6
            
            ##################
            #
            # print
            #
            ##################
            print(f'\nb_J: {bj_reference[j]}')
            print(f'defl_ref: {np.rad2deg(defl_ref)*3600*1e6} muas')
            print(f'dp1_ref: {np.rad2deg(dp1_ref)*3600*1e6} muas')
            print(f'dp2_ref: {np.rad2deg(dp2_ref)*3600*1e6} muas')
            print(f'dp_eta_ref: {np.rad2deg(dp_eta_ref)*3600*1e6} muas')
            print(f'dp_q_eta_ref: {np.rad2deg(dp_q_eta_ref)*3600*1e6} muas\n')
            
    
    shell.append(shell_epoch)
    shell_q.append(shell_q_epoch)


---------- epoch: 2017.1452385988 ----------


b_J: 4.427643850555587

defl_tar: 3818.160305995597 muas
dp1_tar: 1.2480085155419476 muas
dp2_tar: -2.633107797097137 muas
dp_eta_tar: 3818.160208117987 muas
dp_q_eta_tar: 1.247412274953781 muas


b_J: 81.58707469920164
defl_ref: 207.19541198798032 muas
dp1_ref: -0.00039352151664614197 muas
dp2_ref: -0.0002471391755680321 muas
dp_eta_ref: 207.18945333101672 muas
dp_q_eta_ref: -0.00039538449298217644 muas


b_J: 108.15506981721754
defl_ref: 156.29935766256594 muas
dp1_ref: -0.00019890086933502848 muas
dp2_ref: 2.4568423601097757e-05 muas
dp_eta_ref: 156.29486270658694 muas
dp_q_eta_ref: -0.0001986326803983332 muas


b_J: 20.941452965187587
defl_ref: 807.1806418102083 muas
dp1_ref: -0.015776277559318905 muas
dp2_ref: -0.02254487425392974 muas
dp_eta_ref: 807.1574283977776 muas
dp_q_eta_ref: -0.015816678753287402 muas


b_J: 33.30194388495801
defl_ref: 507.6331255830182 muas
dp1_ref: -0.0033251466426465763 muas
dp2_ref: -0.005991673489521589

In [129]:
shell

[array([[3610.97075479, 3661.86534541, 3011.00277972, 3310.54168137,
         3484.83898922, 3665.10380119, 3287.46596524, 3529.64307775,
         2967.81536206, 3422.05294639, 3389.86640266, 3017.39015913,
         2847.97942636, 3538.38906133, 3160.66886604]]),
 array([[3611.43252344, 3662.32593125, 3011.48006599, 3310.99572482,
         3485.29786218, 3665.56458521, 3287.93301976, 3530.1039308 ,
         2968.26261583, 3422.51820512, 3390.33056142, 3017.83429243,
         2848.43667022, 3538.85112708, 3161.14017214]]),
 array([[3611.8947977 , 3662.78702169, 3011.95787067, 3311.45026713,
         3485.75723827, 3666.025874  , 3288.40058434, 3530.5652887 ,
         2968.71036275, 3422.98397235, 3390.79522783, 3018.27891573,
         2848.89441672, 3539.3136987 , 3161.6119918 ]]),
 array([[3612.35717749, 3663.24821768, 3012.43578024, 3311.90491491,
         3486.21671992, 3666.48726834, 3288.86825433, 3531.02675216,
         2969.15821533, 3423.449845  , 3391.25999975, 3018.72364423,
 

In [130]:
shell_q

[array([[1.24780766, 1.24761091, 1.26322895, 1.25075399, 1.24926784,
         1.24756223, 1.24152261, 1.24820844, 1.23005028, 1.24831469,
         1.25130501, 1.26139425, 1.28550716, 1.24854784, 1.25718444]]),
 array([[1.24818122, 1.24798448, 1.26360086, 1.25112781, 1.24964146,
         1.2479358 , 1.24189626, 1.248582  , 1.2304242 , 1.2486882 ,
         1.25167847, 1.26176937, 1.28587939, 1.24892139, 1.25755724]]),
 array([[1.24855524, 1.2483585 , 1.26397322, 1.25150208, 1.25001553,
         1.24830983, 1.24227036, 1.248956  , 1.23079857, 1.24906215,
         1.25205237, 1.26214495, 1.28625207, 1.2492954 , 1.2579305 ]]),
 array([[1.24892939, 1.24873266, 1.26434572, 1.25187648, 1.25038973,
         1.24868398, 1.2426446 , 1.24933014, 1.23117308, 1.24943624,
         1.25242641, 1.26252067, 1.28662489, 1.24966954, 1.25830389]]),
 array([[1.2493037 , 1.24910698, 1.26471837, 1.25225104, 1.25076409,
         1.2490583 , 1.243019  , 1.24970444, 1.23154775, 1.24981049,
         1.25280061, 1

Create data

In [133]:
# angular separation
data_y = []
for epoch in epochs:
    
    print(f'\n---------- epoch: {epoch} ----------\n')
    
    # take only data for the given epoch
    filt = stars_data['tAFx'] == epoch
    stars_epoch = stars_data.loc[filt]
    
    # split into target and reference
    target_df, reference_df = ref_targ_split(stars_epoch)
    
    theta_target = target_df['theta'].to_numpy()
    theta_reference = reference_df['theta'].to_numpy()
    
    r_p = np.zeros((len(target_df), len(reference_df)))
    r_m = np.zeros((len(target_df), len(reference_df)))
    
    eta_targ_p = target_df['etaS[deg]'].to_numpy()
    eta_ref_p = reference_df['etaS[deg]'].to_numpy()
    
    zeta_targ_p = target_df['zetaS[deg]'].to_numpy()
    zeta_ref_p = reference_df['zetaS[deg]'].to_numpy()
    
    x_targ = target_df['starGCdirX'].to_numpy()
    y_targ = target_df['starGCdirY'].to_numpy()
    z_targ = target_df['starGCdirZ'].to_numpy()
    
    x_ref = reference_df['starGCdirX'].to_numpy()
    y_ref = reference_df['starGCdirY'].to_numpy()
    z_ref = reference_df['starGCdirZ'].to_numpy()
    
    
    # loop over target
    for i in range(len(target_df)):
        
        r_targ = np.array([x_targ[i], y_targ[i], z_targ[i]])
        
        # loop over reference
        for j in range(len(reference_df)):
            
            r_ref = np.array([x_ref[j], y_ref[j], z_ref[j]])
            
            r_p[i, j] = np.sqrt((eta_targ_p[i] - eta_ref_p[j])**2 + (zeta_targ_p[i] - zeta_ref_p[j])**2)*3600*1e6
            r_m[i, j] = np.rad2deg(np.arccos(np.dot(r_targ, r_ref))) *3600*1e6
            
            print(f'sep_j: {r_p[i, j]} muas')
            print(f'sep: {r_m[i, j]} muas\n')
            
      
             
                
    data_y.append(np.abs(r_p - r_m))



---------- epoch: 2017.1452385988 ----------

sep_j: 1698939103.036384 muas
sep: 1699023665.0263872 muas

sep_j: 2121871499.9007616 muas
sep: 2121954619.0187488 muas

sep_j: 497370323.4963334 muas
sep: 497419076.0234834 muas

sep_j: 588656744.6182725 muas
sep: 588667389.1310484 muas

sep_j: 958500119.0543888 muas
sep: 958565057.0145519 muas

sep_j: 2189109562.37656 muas
sep: 2189219984.2119365 muas

sep_j: 694035027.9233637 muas
sep: 694076358.7459843 muas

sep_j: 1164200857.102094 muas
sep: 1164279126.4381373 muas

sep_j: 363040488.40607226 muas
sep: 363075162.3847944 muas

sep_j: 936880637.0399202 muas
sep: 936925918.3095059 muas

sep_j: 850879794.1989205 muas
sep: 850943149.5677729 muas

sep_j: 346763672.91755736 muas
sep: 346786064.8158462 muas

sep_j: 338495054.917056 muas
sep: 338535457.8588764 muas

sep_j: 1262604343.9222026 muas
sep: 1262671035.275076 muas

sep_j: 590290735.339834 muas
sep: 590340847.0888053 muas


---------- epoch: 2017.145238752673 ----------

sep_j: 1698936

In [132]:
data_y

[array([[ 84561.99000311,  83119.11798716,  48752.52714998,
          10644.5127759 ,  64937.96016312, 110421.83537626,
          41330.82262063,  78269.33604336,  34673.97872216,
          45281.26958573,  63355.36885238,  22391.89828885,
          40402.94182038,  66691.35287333,  50111.74897134]]),
 array([[ 87533.30668473,  81836.62450886,  47123.25499254,
           9732.5861311 ,  64363.81419611, 106384.23850346,
          40108.94085014,  75948.19845104,  33179.86268526,
          39583.28874958,  58160.87493086,  22748.32053179,
          37087.35529464,  66955.45030403,  50530.79834723]]),
 array([[ 87143.42422056,  82104.4739995 ,  40170.19033331,
          10895.72282875,  64623.18123496, 105988.52735519,
          39388.19892967,  75553.18833899,  33966.27588987,
          34848.72788739,  57594.28241003,  23925.26552486,
          36824.07559276,  66999.2039094 ,  40960.90367246]]),
 array([[ 89215.0915184 ,  82395.03435254,  38611.49680203,
           9234.93092501,  6454